### PR TITLE
make touchSimulation optional

### LINKED ISSUE #16: Make listening to mouse events optional
(Related to issue #5)

There are false positives that appear when using swipe-listener. Specifically, on desktop when selecting/highlighting text, it can register as a swipe event because of swipe-listener listens for mouse events. Would be great to make mouse listening an option that one can disable. In my case, I only need it specifically for mobile/touch-screen enabled devices.

Thanks for your consideration!

### PR DESCRIPTION
**Pull request by r0skar**
This should fix #16. Its pretty basic, but I guess there is nothing wrong with that.

### CODE REVIEW

**Comment by umanghome** [comment]
This approach seems good, but I'm thinking about having flags for both mouse and touch events. Thoughts?

**Comment by r0skar** [comment]
Do you mean a flag to toggle the touch events? It seems to me that the main purpose of this lib is to detect swipe gestures on touch devices, so I am not sure why any1 would want to disable them?

**Comment by umanghome** [comment]
Fair point, but I'm looking at future-proofing this library for the requirement where someone might want it only for mouse events, or only for touch events. It makes more sense to me have flags for both of these.

**Comment by umanghome** [comment]
For example, the consumer of the library can disable listening for touch events and solve #18 without requiring a library update.

**Comment by umanghome** [comment]
Thanks for the PR. Closing this in favor of #21.

**Pull request closed without merging**
