### PR TITLE
Prevent scroll function

### LINKED ISSUE #32: Allow preventScroll to be a function?
I was wondering if you would be open to allowing a function to be passed in for `preventScroll` so the application could make a decision on whether to call `preventDefault`?  I'm still playing around with it a bit, but the current use-case I have is a mobile e-commerce display where there' a main product image that can be swiped left/right to see different images.  But setting `preventScroll: true` makes it such that the user can't scroll by "swiping" up and down on the image either.  And when the image takes up most of the vertical real estate, it there's only small sections that the user can use to scroll the image out of the viewport.

I am experimenting locally with using the event `details` to control whether to `preventDefault` based on the delta between the x coordinates and y coordinates.  

If so, I would be happy to push up a PR once I have something working.

### PR DESCRIPTION
**Pull request by brophdawg11**
Adds support for passing a function for `options.preventScroll(event)` that will allow runtime determination of which events to call `event.preventDefault()` for to prevent scrolling.  This way usage of swipe left/right can prevent scrolling on swipes that are majority left/right, but not on swipes that are majority up/down.

Closes #32

### CODE REVIEW

**Review by umanghome — APPROVED** [review]

**Comment by umanghome** [comment]
Looks good. Thanks for adding this! I'll merge and make a release in a bit.

**Comment by umanghome** [comment]
Released and published in v1.3.0

**Comment by brophdawg11** [comment]
Thanks for the quick turnaround :)

**Comment by handcoding** [comment]
Might anyone be able to elaborate on how this feature can be used to prevent scrolling on swipes that are majority left/right but not on swipes that are majority up/down?

**Pull request merged**
